### ISSUE TITLE
Failing Tests

### ISSUE THREAD

**Issue by mgattozzi** [mgattozzi/curryrs#20]
It seems like there's linkage problems with using `rustup` [now](https://github.com/rust-lang-nursery/rustup.rs/issues/932) until this gets fixed it will cause issues elsewhere and might not let curryrs work at all for that matter.

**Comment by mgattozzi** [comment]
There's finally a fix! [Today I figured out how to get it working](https://twitter.com/mgattozzi/status/953073267920789505) by using a statically compiled version of GHC. Now it'll take a while to get this packaged up and working. It's a bit much so I'll probably start breaking things out into some smaller crates in order to package this up nicely and make it easy to distribute. But now it's unblocked finally!

**Comment by luki** [comment]
Does that mean that at the current time it's still not working properly? (Haven't tested it)

**Comment by mgattozzi** [comment]
Hey @luki, that is correct. I'm currently working on making getting it to work by splitting it out into a separate crate that can be found [here](https://github.com/mgattozzi/ghc-rts-rs). This way you don't need to keep recompiling GHC each time you use this package or hack on it. Once that's all setup I'll be fixing the source code up here further and bring in the fix.

**Comment by mgattozzi** [comment]
@cormacrelf I haven't touched this in awhile, the hack involves a forked version of GHC and making it output static libs. Frankly I would recommend going against this route because even if you got the RTS going I have no idea how you would deal with passing data too and from the lib. You might just be better off calling the pandoc binary tool instead. I also just don't have the bandwidth to work on or support this.

If you want to know where the crate is that does the runtime it's here:
https://github.com/mgattozzi/ghc-rts-rs

The static ghc fork is here:
https://github.com/mgattozzi/ghc-static-8.2.2

**Comment by cormacrelf** [comment]
I’ve poked around a bit (literally) and things aren’t quite as dire as they seem.

First, if you can distribute dylibs, cabal’s foreign-library stanza works pretty well. If you copy each dylib recursively into target/debut and drop the folder structure, cargo run works with just a very basic println in build.rs. That’s because the target folders are all added to the linker path when you cargo run. You could equivalently drop the dylibs in a known location on installation and they would stay intact because of @rpath. Yes, it feels like there’s a lot of unused code in the 37MB libHSpandoc-xxx.dylib file that I would love to LTO out, but this is at least a start, and no bigger than pandoc-citeproc ever was.

The RTS in that configuration works by being dynamically linked into your foreign-library dylib. Slap together a wrapper.c with the usual hs_init boilerplate, and call that from Rust. I think it’s preferable to have the hs_exit function is in a Drop implementation, so that it gets called even when you’re panicking, but I don’t know, that’s just a hunch.

Second, it appears cabal will eventually build static libraries all by itself, with “native-static” instead of “native-shared”. That isn’t implemented yet, but people all over the Haskell world are trying to build even more statically than they already are, so it’s only a matter of time.

Third, yesterday I built a GC-owned string type that can be safely moved into Rust and dropped from there. It contains a StablePtr that the Drop implementation uses to tell Haskell it’s finished and the referenced memory can be GC’d again. This pattern has to be built on ByteString or other types that allocate only in pinned memory, otherwise any derived pointers or slices would get invalidated when RTS rearranges its GC heaps. The HsOwnedString I built consists of struct containing a StablePtr that in Haskell holds a ByteString but in Rust is an opaque machine-word value (in practice, this is a small usize like 0x1e) and a CString pointing to the start of the ByteString’s pinned memory. I will edit this comment later when I’ve pushed the basics, and link to the Reddit thread and the Nginx Haskell module thing I’m drawing from.

**Comment by mgattozzi** [comment]
Closed in https://github.com/mgattozzi/curryrs/commit/4f44de37f51ffbcd3f5136d0e203cbc9259a8316
